#pragma once
#include <lvgl.h>

// Glyph-subset fonts generated by lv_font_conv (see gen_fonts.sh + MANIFEST.md).
// Variable names == generated filenames. hero = 84px digits+symbols; disp = 30px full ASCII;
// body = 18px full ASCII; mono = 15px full ASCII (JetBrains Mono, shared by all themes).
extern const lv_font_t font_sg_hero,    font_sg_disp,    font_sg_body;     // Space Grotesk
extern const lv_font_t font_raj_hero,   font_raj_disp,   font_raj_body;    // Rajdhani
extern const lv_font_t font_doto_hero,  font_doto_disp;                    // Doto
extern const lv_font_t font_cp_hero,    font_cp_disp,    font_cp_body;     // Chakra Petch
extern const lv_font_t font_pix_hero,   font_pix_disp;                     // Pixelify Sans
extern const lv_font_t font_jbm_hero,   font_jbm_disp,   font_jbm_body, font_jbm_mono; // JetBrains Mono
extern const lv_font_t font_inter_hero, font_inter_disp, font_inter_body;  // Inter
